# Generated by Django 5.2.3 on 2025-06-30 15:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SnackCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Auditorium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('total_rows', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('total_cols', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditoriums', to='cinema.cinema')),
            ],
            options={
                'unique_together': {('cinema', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('loyalty_pts', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('original_title', models.CharField(blank=True, max_length=200)),
                ('synopsis', models.TextField(blank=True)),
                ('duration_min', models.PositiveSmallIntegerField(help_text='Duración en minutos')),
                ('release_date', models.DateField()),
                ('rating', models.CharField(help_text='Clasificación, p. ej. PG-13', max_length=10)),
                ('poster', models.ImageField(blank=True, upload_to='posters/')),
                ('trailer_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('genres', models.ManyToManyField(related_name='movies', to='cinema.genre')),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('payment_method', models.CharField(choices=[('CSH', 'Efectivo'), ('CRD', 'Tarjeta'), ('WLT', 'Wallet'), ('PNT', 'Puntos')], max_length=3)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PEN', 'Pendiente'), ('PAI', 'Pagada'), ('CAN', 'Cancelada')], default='PEN', max_length=3)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='cinema.customer')),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveSmallIntegerField()),
                ('col', models.PositiveSmallIntegerField()),
                ('seat_type', models.CharField(default='standard', max_length=20)),
                ('auditorium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='cinema.auditorium')),
            ],
            options={
                'ordering': ('row', 'col'),
                'unique_together': {('auditorium', 'row', 'col')},
            },
        ),
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField()),
                ('language', models.CharField(choices=[('SUB', 'Subtitulada'), ('DUB', 'Doblada')], max_length=20)),
                ('format', models.CharField(choices=[('2D', '2D'), ('3D', '3D'), ('IMAX', 'IMAX')], max_length=10)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('auditorium', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='showtimes', to='cinema.auditorium')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='showtimes', to='cinema.movie')),
            ],
        ),
        migrations.CreateModel(
            name='SnackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(blank=True, upload_to='snacks/')),
                ('is_available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='cinema.snackcategory')),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderSnack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_snacks', to='cinema.order')),
                ('snack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema.snackitem')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('RES', 'Reservado'), ('PAI', 'Pagado'), ('CAN', 'Cancelado')], default='RES', max_length=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('qr_code', models.ImageField(blank=True, upload_to='tickets/qr/')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='cinema.customer')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema.seat')),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='cinema.showtime')),
            ],
            options={
                'ordering': ('showtime', 'seat'),
            },
        ),
        migrations.CreateModel(
            name='OrderTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_tickets', to='cinema.order')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cinema.ticket')),
            ],
        ),
        migrations.AddIndex(
            model_name='showtime',
            index=models.Index(fields=['start_time'], name='cinema_show_start_t_b05ca3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='showtime',
            unique_together={('auditorium', 'start_time')},
        ),
        migrations.AlterUniqueTogether(
            name='ordersnack',
            unique_together={('order', 'snack')},
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('showtime', 'seat')},
        ),
    ]
